name: Test Action CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./
      with:
        message: |
          Workflow test comment
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

